### PR TITLE
Getting Forked version up-to-date

### PR DESCRIPTION
**Pull request by pfkeogh**
Deepdata uses the latest version of master from BigCommerce:master. This will make our fork identical to the main branch. This in preparation to use our own fork instead.

### CODE REVIEW

**Comment by bartboy011** [comment]
@pfkeogh Could we just switch off our fork instead? I'm not sure it's still needed.

**Comment by pfkeogh** [comment]
> @pfkeogh Could we just switch off our fork instead? I'm not sure it's still needed.

By switch off do you mean stop using?

**Comment by bartboy011** [comment]
@pfkeogh Yep! I don't think we need to be using a fork at all, we can just use the version they support instead.

**Comment by pfkeogh** [comment]
As we discussed going to open an issue on BigCommerce and handle the exception in deepdata.

**Pull request closed without merging**
